### ISSUE TITLE
Problem with getcoverage

### ISSUE THREAD

**Issue by fre335** [yuchaojiang/CODEX2#17]
Hello,
I have Problems with running CODEX2. I want to use it for targeted panel CNV detection.
Somehow it does not find the coverage. 

for: head(Y[,1:5]) it fives results like this:

129514_S1 136591_S9 136633_S1 136691_S3 136744_S2
1:26126702-26126925         0         0         0         0         0
1:26127514-26127672         0         0         0         0         0
1:26128487-26128629         0         0         0         0         0
1:26131613-26131787         0         0         0         0         0
1:26135051-26135301         0         0         0         0         0
1:26135497-26135662         0         0         0         0         0

which leads to an error in the next step:

Excluded NA exons due to extreme coverage.
Excluded 0 exons due to extreme exonic length.
Excluded 4 exons due to extreme mappability.
Excluded 1 exons due to extreme GC content.
After taking union, excluded NA out of 1160 exons in QC.
Error: logical subscript contains NAs

As fare as i can see the ref looks ok:

GRanges object with 1160 ranges and 3 metadata columns:
         seqnames              ranges strand |        gc      mapp        gene
            <Rle>           <IRanges>  <Rle> | <numeric> <numeric> <character>
     [1]        1   26126702-26126925      * |     86.16         1    1_gene_1
     [2]        1   26127514-26127672      * |     54.72         1    1_gene_1
     [3]        1   26128487-26128629      * |     51.75         1    1_gene_1
     [4]        1   26131613-26131787      * |     61.14         1    1_gene_1
     [5]        1   26135051-26135301      * |     65.34         1    1_gene_1
     ...      ...                 ...    ... .       ...       ...         ...
  [1156]        X 153608030-153608175      * |      63.7         1   X_gene_39
  [1157]        X 153608282-153608400      * |     49.58         1   X_gene_39
  [1158]        X 153608574-153608748      * |     60.57         1   X_gene_39
  [1159]        X 153609093-153609183      * |     53.85         1   X_gene_39
  [1160]        X 153609222-153609578      * |      59.1         1   X_gene_39

The code i was running looks like this and is basically the same as the in the Demo

bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, 
                       sampname = sampname, projectname = "Codex_test")

bamdir <- bambedObj$bamdir

ref <- bambedObj$ref

sampname <- bambedObj$sampname

projectname <- bambedObj$projectname

gc <- getgc(ref)

mapp <- getmapp(ref)

gene=rep(NA,length(ref))

print(gene)

for(chr in as.matrix(unique(seqnames(ref)))){
  chr.index=which(seqnames(ref)==chr)
  gene[chr.index]=paste(chr,'_gene_',ceiling(chr.index/30),sep='')
}

values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene)) 

coverageObj <- getcoverage(bambedObj, mapqthres = 20)

Y <- coverageObj$Y

write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)
head(Y[,1:5])

qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, Inf),
            length_thresh = c(20, Inf), mapp_thresh = 0.9,
            gc_thresh = c(20, 80))

Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc

does anybody have an idea what the problem could be?
thanks a lot in advance

**Comment by yuchaojiang** [comment]
Hi

thanks for your interest, although I don’t think it is something related to the package.

have you checked whether you have reads in the targets in your bam files? You can do so directly using Samtools or IGV.

If you do have reads, are they paired end or single end? CODEX2 by default requires paired end read.

Yuchao

Sent from my iPhone

On Oct 14, 2019, at 5:40 AM, fre335 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I have Problems with running CODEX2. I want to use it for targeted panel CNV detection.
Somhow it the does not find the coverage.

for: head(Y[,1:5]) it fives results like this:

129514_S1 136591_S9 136633_S1 136691_S3 136744_S2
1:26126702-26126925 0 0 0 0 0
1:26127514-26127672 0 0 0 0 0
1:26128487-26128629 0 0 0 0 0
1:26131613-26131787 0 0 0 0 0
1:26135051-26135301 0 0 0 0 0
1:26135497-26135662 0 0 0 0 0

which leads to an error in the next step:

Excluded NA exons due to extreme coverage.
Excluded 0 exons due to extreme exonic length.
Excluded 4 exons due to extreme mappability.
Excluded 1 exons due to extreme GC content.
After taking union, excluded NA out of 1160 exons in QC.
Error: logical subscript contains NAs

As fare as i can see the ref looks ok:

GRanges object with 1160 ranges and 3 metadata columns:
seqnames ranges strand | gc mapp gene
|
[1] 1 26126702-26126925 * | 86.16 1 1_gene_1
[2] 1 26127514-26127672 * | 54.72 1 1_gene_1
[3] 1 26128487-26128629 * | 51.75 1 1_gene_1
[4] 1 26131613-26131787 * | 61.14 1 1_gene_1
[5] 1 26135051-26135301 * | 65.34 1 1_gene_1
... ... ... ... . ... ... ...
[1156] X 153608030-153608175 * | 63.7 1 X_gene_39
[1157] X 153608282-153608400 * | 49.58 1 X_gene_39
[1158] X 153608574-153608748 * | 60.57 1 X_gene_39
[1159] X 153609093-153609183 * | 53.85 1 X_gene_39
[1160] X 153609222-153609578 * | 59.1 1 X_gene_39

The code i was running looks like this and is basically the same as the in the Demo

bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile,
sampname = sampname, projectname = "Codex_test")

bamdir <- bambedObj$bamdir

ref <- bambedObj$ref

sampname <- bambedObj$sampname

projectname <- bambedObj$projectname

gc <- getgc(ref)

mapp <- getmapp(ref)

gene=rep(NA,length(ref))

print(gene)

for(chr in as.matrix(unique(seqnames(ref)))){
chr.index=which(seqnames(ref)==chr)
gene[chr.index]=paste(chr,'gene',ceiling(chr.index/30),sep='')
}

values(ref) <- cbind(values(ref), DataFrame(gc, mapp, gene))

coverageObj <- getcoverage(bambedObj, mapqthres = 20)

Y <- coverageObj$Y

write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)
head(Y[,1:5])

qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, Inf),
length_thresh = c(20, Inf), mapp_thresh = 0.9,
gc_thresh = c(20, 80))

Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc

**Comment by fre335** [comment]
Hi,

Thanks a lot for your fast reply!

The reads do map to my targets from the bed.file with avarge read depth around 2500 reads.
I am using paired-end reads. Any other ideas what the problem could be? 

Thanks for your help

**Comment by yuchaojiang** [comment]
Hmm weird. This part of the code has been run very extensively by both my group and other users and there’s little change that’s needed.

Have you checked your chr is in the same format between your bam and you bed file?

Also you might want to zoom into the getcoverage function. There’s a line that specifies flag. You might want to comment out or change this. we almost always keep this part unchanged but there might be something specific to your experiment.

Yuchao

Sent from my iPhone

On Oct 14, 2019, at 9:33 AM, fre335 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thanks a lot for your fast reply!

The reads do map to my targets from the bed.file with avarge red depth around 2500 reads.
I am using using paired end reads. Any other ideas what the problem could be?

Thanks for your help

**Comment by fre335** [comment]
it was indeed the chr which has not been the same type as my bed file.....
thanks a lot for the support!

**Comment by yuchaojiang** [comment]
Great. Can you close the issue? Thanks
