### ISSUE TITLE
Need help to understand the choice of optK 

### ISSUE THREAD

**Issue by jekim2022** [yuchaojiang/CODEX2#29]
Hello Dr Yuchao

Thanks to you for your kind and clear reply. I hope you are enjoying this lovely Christmas time :-)  
May I ask you one more question?
In general, the model which has the lowest BIC and RSS evaluated as the most efficient one.
However, CODEX2 determines the latent factor K which has the highest value of BIC. 

Although I guess it is because of CODEX2 may have some different working principles from other programing models, 
I couldn't clear what the difference is. 

So could you give me some clues to clarify why in CODEX2 the K that has the highest value of BIC (instead of the lowest) is recommended as optK? 

**Demo code** is this: 
```
finalcall.CBS <- segmentCBS(Y_qc[chr.index,],  # recommended
                            Yhat.ns, optK = which.max(BIC.ns),
                            K = 1:5,
                            sampname_qc = colnames(Y_qc),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
```

**Comment by yuchaojiang** [comment]
Hi,

Yes, our BIC has a negative sign compared to the traditionally defined BIC. Therefore, we chose the highest BIC (likelihood minus a positive penalty for model complexity).

Sorry for the confusion and I hope that this is helpful!

Yuchao

On Dec 23, 2022, at 7:38 PM, jekim2022 ***@***.******@***.***>> wrote:



Hello Dr Yuchao

Thanks to you for your kind and clear reply. I hope you are enjoying this lovely Christmas time :-)
May I ask you one more question?
In general, the model which has the lowest BIC and RSS evaluated as the most efficient one.
However, CODEX2 determines the latent factor K which has the highest value of BIC.

Although I guess it is because of CODEX2 may have some different working principles from other programing models,
I couldn't clear what the difference is.

So could you give me some clues to clarifying why in CODEX2 the K that has the highest value of BIC (instead of the lowest) is recommended as optK?

Demo code is this:

finalcall.HMM <- segmentHMM(Y_qc[chr.index,],  # not recommended
                            Yhat.ns, optK = which.max(BIC.ns),
                            K = 1:5,
                            sampname_qc = colnames(Y_qc),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, mode = "integer")
