### ISSUE TITLE
Questions about "Running CODEX2 without specifying negative control samples/regions"

### ISSUE THREAD

**Issue by shexuan** [yuchaojiang/CODEX2#6]
Hi, I have 49 uncorrelated samples and run in batch with CODEX2  without specifying negative control samples/regions. But the results is quit terrible, the number of cnv were few and only detected chr1,chr2 and chr3, and even some samples could not find any cnv (One of the sample is NA12878). I was wondering where is wrong in my code:
```
library(CODEX2)
library(WES.1KG.WUGSC) # Load Toy data from the 1000 Genomes Project.

###################################################################################
# Pre-processing

bamFile <- list.files('/storage/wujh/Project/CNV_analysis/CODEX/bam', pattern = '*.bam$') 
bamdir <- file.path('/storage/wujh/Project/CNV_analysis/CODEX/bam', bamFile)
sampname <- substr(bamFile,1,8)
bedFile <- file.path('/home/sxuan/codex2', 'AgV6.bed')
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile, 
                       sampname = sampname, projectname = 'CODEX2_test')
bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
ref <- bambedObj$ref; projectname <- bambedObj$projectname


###################################################################################
# Getting GC content and mappability

gc <- getgc(ref, genome = BSgenome.Hsapiens.UCSC.hg19)
mapp <- getmapp(ref, genome = BSgenome.Hsapiens.UCSC.hg19)
values(ref) <- cbind(values(ref), DataFrame(gc, mapp))


####################################################################################
# Getting raw read depth

coverageObj <- getcoverage(bambedObj, mapqthres = 20)
Y <- coverageObj$Y
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)


####################################################################################
# Quality control

print('Quality control')
qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, Inf),
            length_thresh = c(20, Inf), mapp_thresh = 0.9,
            gc_thresh = c(20, 80))
Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc
ref_qc <- qcObj$ref_qc; qcmat <- qcObj$qcmat; gc_qc <- ref_qc$gc
write.table(qcmat, file = paste(projectname, '_qcmat', '.txt', sep=''),
            sep = '\t', quote = FALSE, row.names = FALSE)


###################################################################################
# Running CODEX2
print('Running CODEX2')

Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x){!any(x==0)}),]
pseudo.sample <- apply(Y.nonzero,1,function(x){prod(x)^(1/length(x))})
N <- apply(apply(Y.nonzero, 2, function(x){x/pseudo.sample}), 2, median)

# Running CODEX2 without negative control samples/regions

print('Running CODEX2 without negative control samples/regions')
chr <- c(c(1:22),'X','Y')

chr.index <- which(seqnames(ref_qc)==chr)
norm_index <- c(1:length(sampname))

normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                           gc_qc = gc_qc[chr.index],
                           K = 1:5, N = N)
Yhat.null <- normObj.null$Yhat
AIC.null <- normObj.null$AIC; BIC.null <- normObj.null$BIC
RSS.null <- normObj.null$RSS

#Choose the number of latent Poisson factors. BIC is used as the model selection metric by default.
choiceofK(AIC.null, BIC.null, RSS.null, K = 1:5 , filename = "codex2_null_choiceofK.pdf")
par(mfrow = c(1, 3))
plot(1:5, RSS.null, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:5, AIC.null, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:5, BIC.null, type = "b", xlab = "Number of latent variables", pch=20)
par(mfrow = c(1,1))

##################################################################################
# Running segmentation by CODEX2
print('Running segmentation by CODEX2')
# recommended
finalcall.CBS <- segmentCBS(Y_qc[chr.index,],  
                            Yhat.null, optK = which.max(BIC.null),
                            K = 1:5,
                            sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
write.table(finalcall.CBS, file=paste('norm_null.final.cnv',sep=''), sep='\t', quote=F)

# not recommended
# finalcall.HMM <- segmentHMM(Y_qc[chr.index,],  
#                             Yhat.ns, optK = which.max(BIC.ns),
#                             K = 1:5,
#                             sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
#                             ref_qc = ranges(ref_qc)[chr.index],
#                             chr = chr, mode = "integer")


# Post-segmentation pruning and filtering are recommended based on CNV length (filter1), 
# length per exon (filter2), likelihood ratio (filter3), and number of exons (filter4)

filter1 <- finalcall.CBS$length_kb<=200
filter2 <- finalcall.CBS$length_kb/(finalcall.CBS$ed_exon-finalcall.CBS$st_exon+1)<50
finalcall.CBS.filter <- finalcall.CBS[filter1 & filter2, ]

filter3 <- finalcall.CBS.filter$lratio>40
filter4 <- (finalcall.CBS.filter$ed_exon-finalcall.CBS.filter$st_exon)>1
finalcall.CBS.filter=finalcall.CBS.filter[filter3|filter4,]

write.table(finalcall.CBS.filter, file='_norm_null.final.filtered.cnv', sep='\t', quote=F)
``` 
Any suggestions will be greatly appreciated !

**Comment by yuchaojiang** [comment]
The results are terrible most likely due to how you set up your run. You said that you had 49 samples and ran them in batches. How many samples per batch did you run CODEX2 on? What is the optimal number of K for each run? If you only have around tens samples with a high number of K, you won’t have germline CNV calls. Also you need to specify the normal Cnv index if you want to force call CNVs in your 1000GP samples. The index can be obtained from IGV or can be obtained from a first run of CODEX2 by looking at the standard deviations of the normalized z scores for each exon across all samples. The z-scores are the log ratios of Y over lambda. Obviously the latter approach needs user tuning and is data specific and thus the threshold is not prefixed in our pipeline.

Sent from my iPhone

On Sep 26, 2018, at 5:28 AM, shexuan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I have 49 uncorrelated samples and run in batch with CODEX2 without specifying negative control samples/regions. But the results is quit terrible, cnv were only detected chr1,chr2 and chr3, and the even some samples could not find any cnv (One of the sample is NA12878). I was wondering where is wrong in my code:

library(CODEX2)
library(WES.1KG.WUGSC) # Load Toy data from the 1000 Genomes Project.

###################################################################################
# Pre-processing

bamFile <- list.files('/storage/wujh/Project/CNV_analysis/CODEX/bam', pattern = '*.bam$')
bamdir <- file.path('/storage/wujh/Project/CNV_analysis/CODEX/bam', bamFile)
sampname <- substr(bamFile,1,8)
bedFile <- file.path('/home/sxuan/codex2', 'AgV6.bed')
bambedObj <- getbambed(bamdir = bamdir, bedFile = bedFile,
                       sampname = sampname, projectname = 'CODEX2_test')
bamdir <- bambedObj$bamdir; sampname <- bambedObj$sampname
ref <- bambedObj$ref; projectname <- bambedObj$projectname


###################################################################################
# Getting GC content and mappability

gc <- getgc(ref, genome = BSgenome.Hsapiens.UCSC.hg19)
mapp <- getmapp(ref, genome = BSgenome.Hsapiens.UCSC.hg19)
values(ref) <- cbind(values(ref), DataFrame(gc, mapp))


####################################################################################
# Getting raw read depth

coverageObj <- getcoverage(bambedObj, mapqthres = 20)
Y <- coverageObj$Y
write.csv(Y, file = paste(projectname, '_coverage.csv', sep=''), quote = FALSE)


####################################################################################
# Quality control

print('Quality control')
qcObj <- qc(Y, sampname, ref, cov_thresh = c(20, Inf),
            length_thresh = c(20, Inf), mapp_thresh = 0.9,
            gc_thresh = c(20, 80))
Y_qc <- qcObj$Y_qc; sampname_qc <- qcObj$sampname_qc
ref_qc <- qcObj$ref_qc; qcmat <- qcObj$qcmat; gc_qc <- ref_qc$gc
write.table(qcmat, file = paste(projectname, '_qcmat', '.txt', sep=''),
            sep = '\t', quote = FALSE, row.names = FALSE)


###################################################################################
# Running CODEX2
print('Running CODEX2')

Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x){!any(x==0)}),]
pseudo.sample <- apply(Y.nonzero,1,function(x){prod(x)^(1/length(x))})
N <- apply(apply(Y.nonzero, 2, function(x){x/pseudo.sample}), 2, median)

# Running CODEX2 without negative control samples/regions

print('Running CODEX2 without negative control samples/regions')
chr <- c(c(1:22),'X','Y')

chr.index <- which(seqnames(ref_qc)==chr)
norm_index <- c(1:length(sampname))

normObj.null <- normalize_null(Y_qc = Y_qc[chr.index,],
                           gc_qc = gc_qc[chr.index],
                           K = 1:5, N = N)
Yhat.null <- normObj.null$Yhat
AIC.null <- normObj.null$AIC; BIC.null <- normObj.null$BIC
RSS.null <- normObj.null$RSS

#Choose the number of latent Poisson factors. BIC is used as the model selection metric by default.
choiceofK(AIC.null, BIC.null, RSS.null, K = 1:5 , filename = "codex2_null_choiceofK.pdf")
par(mfrow = c(1, 3))
plot(1:5, RSS.null, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:5, AIC.null, type = "b", xlab = "Number of latent variables", pch=20)
plot(1:5, BIC.null, type = "b", xlab = "Number of latent variables", pch=20)
par(mfrow = c(1,1))

##################################################################################
# Running segmentation by CODEX2
print('Running segmentation by CODEX2')
# recommended
finalcall.CBS <- segmentCBS(Y_qc[chr.index,],
                            Yhat.null, optK = which.max(BIC.null),
                            K = 1:5,
                            sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
write.table(finalcall.CBS, file=paste('norm_null.final.cnv',sep=''), sep='\t', quote=F)

# not recommended
# finalcall.HMM <- segmentHMM(Y_qc[chr.index,],
#                             Yhat.ns, optK = which.max(BIC.ns),
#                             K = 1:5,
#                             sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
#                             ref_qc = ranges(ref_qc)[chr.index],
#                             chr = chr, mode = "integer")


# Post-segmentation pruning and filtering are recommended based on CNV length (filter1),
# length per exon (filter2), likelihood ratio (filter3), and number of exons (filter4)

filter1 <- finalcall.CBS$length_kb<=200
filter2 <- finalcall.CBS$length_kb/(finalcall.CBS$ed_exon-finalcall.CBS$st_exon+1)<50
finalcall.CBS.filter <- finalcall.CBS[filter1 & filter2, ]

filter3 <- finalcall.CBS.filter$lratio>40
filter4 <- (finalcall.CBS.filter$ed_exon-finalcall.CBS.filter$st_exon)>1
finalcall.CBS.filter=finalcall.CBS.filter[filter3|filter4,]

write.table(finalcall.CBS.filter, file='_norm_null.final.filtered.cnv', sep='\t', quote=F)


Any suggestions will be greatly appreciated !

**Comment by shexuan** [comment]
@yuchaojiang 
Thanks a lot for your suggestions. I ran the whole 49 samples in a batch and normlized with function normalize_null, cuase I want to utilize CODEX2 in a germline cnv-pipe, it's hard to tunning parameters when running different samples. So, will this be possible to set some fixed or default parameters for each run, such as K=5 and normlizing with function nomalize_null (it may be difficult to set cnv index for different runs of different samples) ?

**Comment by yuchaojiang** [comment]
Not sure I got what you meant. If you need further help, please clearly state your experimental design and how you run CODEX2. You mentioned that you run all 49 samples in one batch yet also said default parameters for each run? The number of latent factors is data set specific. If you only have 49 samples and they are all from one batch, optK=5 might be too large and thus removing all CNV signals.

**Comment by shexuan** [comment]
@yuchaojiang 
Sorry for my poor english. Here I got 49 uncorrelated WES samples and wanted to call cnv for all this samples to be compared with other softwares  such as XHMM, CNVnator. I ran all 49 samples [without specifying negative control samples/regions ](https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.Rmd#running-codex2-without-specifying-negative-control-samplesregions).
The normlizing function is `normalize_null(Y_qc = Y_qc[chr.index,], gc_qc = gc_qc[chr.index], K = 1:5, N = N)`, and optK is automatically set according BIC in 
```
finalcall.CBS <- segmentCBS(Y_qc[chr.index,],  
                            Yhat.null, optK = which.max(BIC.null),
                            K = 1:5,
                            sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
```

**Comment by yuchaojiang** [comment]
What is optimal K you chose? How does AIC, BIC, and variance reduction plot look?

On Sep 26, 2018, at 10:03 PM, shexuan <notifications@github.com<mailto:notifications@github.com>> wrote:


@yuchaojiang<https://github.com/yuchaojiang>
Sorry for my poor english. Here I got 49 uncorrelated WES samples and wanted to call cnv for all this samples to be compared with other softwares such as XHMM, CNVnator. I ran all 49 samples without specifying negative control samples/regions <https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.Rmd#running-codex2-without-specifying-negative-control-samplesregions> .
The normlizing function is normalize_null(Y_qc = Y_qc[chr.index,], gc_qc = gc_qc[chr.index], K = 1:5, N = N), and optK is automatically set according BIC in

finalcall.CBS <- segmentCBS(Y_qc[chr.index,],
                            Yhat.null, optK = which.max(BIC.null),
                            K = 1:5,
                            sampname_qc = paste('sample',1:ncol(Y_qc),sep=''),
                            ref_qc = ranges(ref_qc)[chr.index],
                            chr = chr, lmax = 400, mode = "integer")
