### ISSUE TITLE
missing or infinite values in inputs are not allowed

### ISSUE THREAD

**Issue by thedam** [yuchaojiang/CODEX2#7]
Hi,
I follow this tutorial: http://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html

I have ~180 bam files that came from the same lab, but in different time periods (batches of 9-15 files).
When I analyze them together I get error:

```
Error in smooth.spline(gc_qc, z) : 
  missing or infinite values in inputs are not allowed
```

(maybe it comes from:
```
> pseudo.sample
  1:861321-861393   1:865534-865716   1:866418-866469   1:871151-871276   1:874419-874509   1:874654-874840   1:876523-876686   1:877938-878438 
              Inf               Inf               Inf               Inf               Inf               Inf               Inf               Inf 
  1:878632-878757   1:879077-879188   1:879287-879533   1:880073-880180   1:880436-880526   1:880897-881033   1:881552-881666   1:881781-881925 
              Inf  
```
)

are there some methods, to firstly run "batches" separately, and then merge the results and follow the tutorial?

Thanks for any advice,
Damian

**Comment by yuchaojiang** [comment]
Hi,

It’s hard to tell what is wrong with this error message only. How many samples did you run CODEX2 with? Can you send in *.rda file for us  to better help you?

Yuchao

On Sep 27, 2018, at 5:27 AM, Damian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I follow this tutorial: http://htmlpreview.github.io/?https://github.com/yuchaojiang/CODEX2/blob/master/demo/CODEX2.html

I have ~180 bam files that came from the same lab, but in different time periods (batches of 9-15 files).
When I analyze them together I get error:

Error in smooth.spline(gc_qc, z) :
  missing or infinite values in inputs are not allowed


(maybe it comes from:

> pseudo.sample
  1:861321-861393   1:865534-865716   1:866418-866469   1:871151-871276   1:874419-874509   1:874654-874840   1:876523-876686   1:877938-878438
              Inf               Inf               Inf               Inf               Inf               Inf               Inf               Inf
  1:878632-878757   1:879077-879188   1:879287-879533   1:880073-880180   1:880436-880526   1:880897-881033   1:881552-881666   1:881781-881925
              Inf


)

are there some methods, to firstly run "batches" separately, and then merge the results and follow the tutorial?

Thanks for any advice,
Damian

**Comment by bwubb** [comment]
I am also experiencing this error, as well as de ja vu because I feel like Ive corrected this and now cant remember how. Anyway,

```
> normObj<-normalize_codex2_ns(Y_qc=Y_qc[chr.index,],gc_qc=gc_qc[chr.index],K=1:10,norm_index=norm_index,N=N)
Computing normalization with k = 1 latent factors ...
k = 1
Error in smooth.spline(gc_qc, z) :
  missing or infinite values in inputs are not allowed
```
Earlier parts of codex2 ran just fine as far as I can tell. I am running this portion as a separate script so I am trying to read in the coverage qc data from saved csv files. Then I want to subset to chr1. Perhaps I have done that portion incorrectly?

```
bedFile<-'SureSelect-Exon_v6+COSMIC.S07604715.Covered.bed'
exomtarg <- read.table(bedFile, sep = "\t")
ref <- GRanges(seqnames=exomtarg[,1],ranges=IRanges(start=exomtarg[,2], end=exomtarg[,3]))
ref <- sort(ref)
### Running CODEX2 with Negative Control Samples###

Y_qc <- read.csv(paste(projectname,'coverageQC.csv',sep='/'),row.names=1,check.names=FALSE)
Y_qc<-as.matrix(Y_qc)

qcmat<-read.csv(file=paste(projectname,'qcmat.csv',sep='/'),header=TRUE)
ind<-qcmat$pass==TRUE
ref_qc<-ref[ind]

gc<-getgc(ref_qc)
mapp<-getmapp(ref_qc)
values(ref_qc)<-cbind(values(ref_qc), DataFrame(gc, mapp))
gc_qc<-read.csv(paste(projectname,'gc_qc.csv',sep='/'),row.names=1,check.names=FALSE)
gc_qc<-as.numeric(gc_qc[,'x'])

N<-read.csv(paste(projectname,'library_size_factor.csv',sep='/'))
N<-as.numeric(N[,'x'])
norm_index<-which(colnames(Y_qc) %in% normal_samples$V1)
sampname_qc<-colnames(Y_qc)
chr.index<-which(seqnames(ref_qc)==chr)
```

Thanks

**Comment by yuchaojiang** [comment]
Hi Brad,

I think this may be caused by overflow when the old version reconstructed the pseudo-reference. Did you use the code below for the step prior to normalization?

Y.nonzero <- Y_qc[apply(Y_qc, 1, function(x){!any(x==0)}),]
pseudo.sample <- apply(Y.nonzero,1,function(x){exp(1/length(x)*sum(log(x)))})
N <- apply(apply(Y.nonzero, 2, function(x){x/pseudo.sample}), 2, median)

Thanks!
Yuchao

**Comment by bwubb** [comment]
Thanks Yuchao. My pseudo.sample line appears to be different. I must have copied it from my targeted_germline version? Because it was this.

```
pseudo.sample<-apply(Y.nonzero,1,function(x){prod(x)^(1/length(x))})
````
Is the change to,
`
pseudo.sample <- apply(Y.nonzero,1,function(x){exp(1/length(x)*sum(log(x)))})
`
just for the WES negative control pipeline or should it be applied elsewhere?

Thanks really appreciated.

**Comment by yuchaojiang** [comment]
Yes it should be applied to all CODEX2 pipeline. The two lines should give the same result — only that the first one would lead to overflow error by (x)!

On Feb 26, 2019, at 2:28 PM, Brad Wubbenhorst <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Yuchao. My pseudo.sample line appears to be different. I must have copied it from my targeted_germline version? Because it was this.

pseudo.sample<-apply(Y.nonzero,1,function(x){prod(x)^(1/length(x))})


Is the change to,
pseudo.sample <- apply(Y.nonzero,1,function(x){exp(1/length(x)*sum(log(x)))})
just for the WES negative control pipeline or should it be applied elsewhere?

Thanks really appreciated.
